POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Bruna",
    "email": "brubzz@Labenu.com.br",
    "password": "12345689"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "jardimbotanico.png",
    "description": "Imagem do jardim botanico do Curitiba",
    "type": "normal",
    "author_id": "f08a8e98-88a5-42ac-a6cc-67fc49277652"
}