POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Bruna2",
    "email": "brubzz2@Labenu.com.br",
    "password": "12345689"
}

###

POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "pracatiradentes.png",
    "description": "Imagem da praça tiradentes de Curitiba",
    "type": "normal",
    "author_id": "f08a8e98-88a5-42ac-a6cc-67fc49277652"
}