POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Teste1",
    "email": "lamarr@Labenu.com.br",
    "password": "12345689"
}

###

POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "lua.png",
    "description": "lua cheia vista em Curitiba.",
    "type": "normal",
    "author_id": "1a65083e-19e9-4b20-bc0f-32e0110820b7"
}

###

GET http://localhost:3003/post/posts/0832ac50-439b-48c5-9037-4c966c80c14b


